# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "ng-demo-app-api.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "ng-demo-app-api.dll"]

# Build Image
# docker build --rm -f dockerfile -t ng-demo-app-api .
# docker run -it --rm -p 5051:80 ng-demo-app-api

# docker tag ng-demo-app-api arambazamba/ng-demo-app-api
# docker push arambazamba/ng-demo-app-api

# Injecting environment variables into the container
# docker run -it --rm -p 5051:80 ng-demo-app-api -e "App:AuthEnabled"="false"

# Browse using: 
# http://localhost:5051
# http://localhost:5051/food
# http://localhost:5051/env